sudo: false
dist: trusty

language: php
php: 7.1

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - ./ci/prepare.sh

jobs:
  include:
    - stage: test
      script: ./ci/test.sh
      php: 5.3
      dist: precise
      env: WP_VERSION=3.7.11

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^release-.+$/

notifications:
  email:
    on_success: never
    on_failure: change
