language: php

php:
  - 5.3
  - 5.5

env:
  - WP_VERSION=latest 
  - WP_VERSION=3.4.2

matrix:
  exclude:
    - php: 5.5
      env: WP_VERSION=3.4.2

before_script: ./bin/ci/install_dependencies.sh

script: ./bin/ci/run_build.sh

notifications:
  email:
    on_success: never
